version: '3'

services:
  pgsql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - '5444:5432'
    networks:
      - internal
    volumes:
      - ./db/db-data:/var/lib/postgresql/data

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/app
    depends_on:
      - pgsql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8876:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/app
    depends_on:
      - php-fpm

networks:
  internal:
