### application-create
POST http://localhost:8876/api/application-create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "topic": "новый топик",
  "message": "месстаге новый"
}

### applications-show
GET http://localhost:8876/api/applications-show
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### applications-show-user
GET http://localhost:8876/api/applications-show-user
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### application-show/{id}
GET http://localhost:8876/api/application-show/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### /api/application-status-check/{id}
GET http://localhost:8876/api/application-status-check/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### /api/application-status-edit
POST http://localhost:8876/api/application-status-edit
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 1,
  "status": 3,
  "comment": "новый коммент"
}