### создаем новую заявку
POST http://localhost:8876/api/application-create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "topic": "новый топик 2 4",
  "message": "месстаге новый 3 4"
}

### получение списка своих заявок
GET http://localhost:8876/api/applications-show-user
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### получить статус заявки
GET http://localhost:8876/api/application-status-check/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### просмотр всех заявок / менеджер
GET http://localhost:8876/api/applications-show
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### изменение статуса / менеджер
POST http://localhost:8876/api/application-status-edit
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 1,
  "status": 3,
  "comment": "новый коммент"
}

### просмотр заявки пользователем
GET http://localhost:8876/api/application-show/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}





